env:
  GGBB: "bbgg"

steps:

  - label: "define if for full test suite"
    if: build.pull_request.base_branch == "develop" && !build.pull_request.draft
    command: buildkite-agent meta-data set "full_test_suite" "true" && export GGGG="lkadjsflkdjsa;flj"
    agents:
      queue: "testing"

  - wait

  - label: "print environment"
    command: echo "full_test_suite:" ${GGBB} -${GGGG} - $(buildkite-agent meta-data get "full_test_suite" --default "false")
    agents:
      queue: "testing"


  - wait

  - label: ":docker: trigger python logged groups pipeline"
    trigger: "rozhkovdmitrii-sanbox-pipeline"
    build:
      branch: "play-buildkite"
      env:
          EVM_LOADER_REVISION: "${BUILDKITE_COMMIT}"
          EVM_LOADER_BRANCH: "${EVM_LOADER_BRANCH}"
          SOLANA_REVISION: "v1.8.12-testnet"
          EVM_LOADER_DEVELOP_NOT_DRAFT_PR: $(buildkite-agent meta-data get "full_test_suite" --default "false")

      meta_data:
        evm_loader_branch: "${BUILDKITE_BRANCH}"
        evm_loader_develop_not_draft_pr: $(buildkite-agent meta-data get "non_draft" --default "false")


