steps:

  - label: "about to trigger python-logged-gorups pipeline"
    command: echo "trigger pipeline"
  - label: ":docker: trigger python logged groups pipeline"
    trigger: "rozhkovdmitrii_sanbox_pipeline"
    build:
      branch: "play-buildkite"
      env:
          EVM_LOADER_REVISION: "${BUILDKITE_COMMIT}"
          EVM_LOADER_BRANCH: "${EVM_LOADER_BRANCH}"
          SOLANA_REVISION: "v1.8.12-testnet"

