
steps:

  - label: "define if for full test suite"
    if: build.pull_request.base_branch == "develop" && !build.pull_request.draft
    commands:
      - buildkite-agent meta-data set "full_test_suite" "true"
    agents:
      queue: "testing"

  - wait

  - label: ":docker: Up dynamic pipeline"
    command: ./.buildkite/steps/trigger-proxy-step.sh | buildkite-agent pipeline upload




