steps:

  - label: "about to trigger python-logged-gorups pipeline"
    command: echo trigger pipeline ${BUILDKITE_PULL_REQUEST_DRAFT}
  - label: "define if for full test suite"
    if: build.pull_request.draft
    command: buildkite-agent meta-data set "is_draft_pull_requeset" "true"
  - label: ":docker: trigger python logged groups pipeline"
    trigger: "rozhkovdmitrii-sanbox-pipeline"
    build:
      branch: "play-buildkite"
      env:
          EVM_LOADER_REVISION: "${BUILDKITE_COMMIT}"
          EVM_LOADER_BRANCH: "${EVM_LOADER_BRANCH}"
          SOLANA_REVISION: "v1.8.12-testnet"

      meta_data:
        evm_loader_branch: "${BUILDKITE_BRANCH}"


