steps:

  - label: "define if for full test suite"
    if: build.pull_request.draft
    command: "echo set up DRAFT environment"
    agents:
      queue: "testing"
    env:
      DRAFT: "true"

  - label: "print environment"
    command: echo "draft:" ${DRAFT}
    agents:
      queue: "testing"
#
#  - wait
#  - label: ":docker: trigger python logged groups pipeline"
#    trigger: "rozhkovdmitrii-sanbox-pipeline"
#    build:
#      branch: "play-buildkite"
#      env:
#          EVM_LOADER_REVISION: "${BUILDKITE_COMMIT}"
#          EVM_LOADER_BRANCH: "${EVM_LOADER_BRANCH}"
#          SOLANA_REVISION: "v1.8.12-testnet"
#
#      meta_data:
#        evm_loader_branch: "${BUILDKITE_BRANCH}"
#        draft: build.env("DRAFT")
#
#
