steps:

  - label: "define if for full test suite"
    if: build.pull_request.draft
    commands:
      - "DRAFT=true"
      - "export DRAFT"
    agents:
      queue: "testing"

  - label: "print environment"
    command: echo "draft:" ${DRAFT} GITHUB_RELEASE_ACCESS_KEY ${GITHUB_RELEASE_ACCESS_KEY}
