
steps:

  - label: "define if for full test suite"
    if: build.pull_request.base_branch == "develop" && !build.pull_request.draft
    commands:
      - buildkite-agent meta-data set "full_test_suite" "true"
      - echo NEON_EVM_PR_DEVELOP=${BUILDKITE_PULL_REQUEST} > neon_evm_pipeline.env
      - echo BUILDKITE_JOB_ID - ${BUILDKITE_JOB_ID}
    agents:
      queue: "testing"
    artifact_paths:
      - "neon_evm_pipeline.env"


  - wait

  - label: "print environment"
    commands:
      - echo $(buildkite-agent meta-data get "full_test_suite" --default "false") > neon_evm_pipeline_data.env
      - echo BUILDKITE_JOB_ID - ${BUILDKITE_JOB_ID}
    agents:
      queue: "testing"
    artifact_paths:
      - "neon_evm_pipeline.env"

  - wait

  - label: ":docker: trigger python logged groups pipeline"
    command: ./.buildkite/steps/trigger-proxy-pipeline.sh | buildkite-agent pipeline upload




