steps:

  - label: "define if for full test suite"
    if: build.pull_request.draft
    command: export DRAFT=true
    agents:
      queue: "testing"

  - label: "print environment"
    command: echo "draft:" ${DRAFT}
