[package]
name = "neon-cli"
version = "0.5.4-dev"
authors = ["Cyber-Core Maintainers <maintainers@cyber-core.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4.19"
thiserror = "1.0.30"
num-derive = "0.3.3"
num-traits = "0.2.14"
num_enum = "0.5.6"
bincode = "1.3.3"
clap = "2.34.0"
evm-loader = { path = "../program", default_features = false }
evm = { path = "../rust-evm", version = "0.18", default_features = false }
solana-sdk = "=1.7.9"
solana-client = "=1.7.9"
solana-clap-utils = "=1.7.9"
solana-cli-config = "=1.7.9"
solana-cli = "=1.7.9"
solana-cli-output = "=1.7.9"
solana-transaction-status = "=1.7.9"
spl-token = { version = "3.2.0", default_features = false, features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.0.3", default_features = false, features = ["no-entrypoint"] }
bs58 = "0.4.0"
hex = "0.4.3"
sha3 = "0.8.2"
arrayref = "0.3.6"
serde = "1.0.134"
serde_json = "1.0.75"
getrandom = { version = "0.1.16", default_features = false, features = ["dummy"] }
libsecp256k1 = { version = "0.5.0", default-features = false }
log = "0.4.14"
fern = "0.6.0"
rlp = "0.5.1"
solana-program = { version = "1.7.9", default_features = false }
rand = "0.7.3"
ethereum-types = "0.12.1"
base64 = { version = "0.13.0" }
goblin = { version = "0.4.3" }
